%% Data Analysis
%% Spectral slope of average SFs from figure in SF_plot*.m:
%% Mean

clc ; close all

FitBasisFunction = {'a*t.^b','a','b'};
FitParameters0 = [0.1,1.5];
FitBasisDerivatives = {'t.^b','a*log(t).*t.^b'};
ToleranceLevel = 0.00001; % NLLSF parameter, tells change in parameter magnitude, if small then the result was stable
N_nllsf_iterations = 10; % number of iterations before we give up

% % % SWOT_at_S_P_G
LEG_TEXT = {LEG_TEXT{:},'SWOT cal/val at Moorings+Gliders'};
BIN_EDGES = [(-dBIN/2):[dBIN]:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_SWOT_moor_12hr,Separation_SWOT_moor_12hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_SWOT_moor_12hr, m2_to_cm2*StructFunc_SWOT_moor_12hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['SWOT 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(Mean_SF_MAT_swot(2:dsearchn(DIST_VEC,40)), DIST_VEC(2:dsearchn(DIST_VEC,40)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,40))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(Mean_SF_MAT_swot(2:dsearchn(DIST_VEC,90)), DIST_VEC(2:dsearchn(DIST_VEC,90)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,90))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.1hr
LEG_TEXT = {LEG_TEXT{:},'Moorings (600m, 1hr)'};
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_1hr,Separation_S_P_600m_1hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_1hr, m2_to_cm2*StructFunc_S_P_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m/1hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.24hr
LEG_TEXT = {LEG_TEXT{:},'Moorings (600m, 24hr)'};
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_24hr,Separation_S_P_600m_24hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_24hr, m2_to_cm2*StructFunc_S_P_600m_24hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SPG.600m.1hr
LEG_TEXT = {LEG_TEXT{:},'Moorings+Gliders (600m, 1hr)'};
BIN_EDGES = [(-dBIN/2/2):[dBIN/2]:[14*dBIN/2/2]]; BIN_EDGES =  [BIN_EDGES, [BIN_EDGES(end)+dBIN]:[dBIN]:1.1]*(0.92)*DD;% initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_G_600m_1hr,Separation_S_P_G_600m_1hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_G_600m_1hr, m2_to_cm2*StructFunc_S_P_G_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(8:[end-1]),BIN_CENTR(8:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/MG 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:8),BIN_CENTR(2:8),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR(8)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


%% Mean + std_of_mean

close all
disp(['%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'])

FitBasisFunction = {'a*t.^b','a','b'};
FitParameters0 = [0.1,1.5];
FitBasisDerivatives = {'t.^b','a*log(t).*t.^b'};
ToleranceLevel = 0.00001; % NLLSF parameter, tells change in parameter magnitude, if small then the result was stable
N_nllsf_iterations = 10; % number of iterations before we give up

% % % SWOT_at_S_P_G
BIN_EDGES = [(-dBIN/2):[dBIN]:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_SWOT_moor_12hr,Separation_SWOT_moor_12hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_SWOT_moor_12hr, m2_to_cm2*StructFunc_SWOT_moor_12hr, BIN_EDGES) + ...
         interval_stdofmean(Separation_SWOT_moor_12hr, m2_to_cm2*StructFunc_SWOT_moor_12hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['SWOT 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')
SF_avg = mean(SF_MAT_swot,2,'omitnan') + std(SF_MAT_swot,0,2,'omitnan')./sqrt(sum(isfinite(SF_MAT_swot(:,:)), 2));
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:dsearchn(DIST_VEC,40)), DIST_VEC(2:dsearchn(DIST_VEC,40)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,40))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:dsearchn(DIST_VEC,90)), DIST_VEC(2:dsearchn(DIST_VEC,90)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,90))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.1hr
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_1hr,Separation_S_P_600m_1hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_1hr, m2_to_cm2*StructFunc_S_P_600m_1hr, BIN_EDGES) + ...
         interval_stdofmean(Separation_S_P_600m_1hr, m2_to_cm2*StructFunc_S_P_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m/1hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.24hr
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_24hr,Separation_S_P_600m_24hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_24hr, m2_to_cm2*StructFunc_S_P_600m_24hr, BIN_EDGES) + ...
         interval_stdofmean(Separation_S_P_600m_24hr, m2_to_cm2*StructFunc_S_P_600m_24hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SPG.600m.1hr
BIN_EDGES = [(-dBIN/2/2):[dBIN/2]:[14*dBIN/2/2]]; BIN_EDGES =  [BIN_EDGES, [BIN_EDGES(end)+dBIN]:[dBIN]:1.1]*(0.92)*DD;% initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_G_600m_1hr,Separation_S_P_G_600m_1hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_G_600m_1hr, m2_to_cm2*StructFunc_S_P_G_600m_1hr, BIN_EDGES) + ...
         interval_stdofmean(Separation_S_P_G_600m_1hr, m2_to_cm2*StructFunc_S_P_G_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(8:[end-1]),BIN_CENTR(8:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/MG 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:8),BIN_CENTR(2:8),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR(8)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


%% Mean - std_of_mean

close all
disp(['%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'])

FitBasisFunction = {'a*t.^b','a','b'};
FitParameters0 = [0.1,1.5];
FitBasisDerivatives = {'t.^b','a*log(t).*t.^b'};
ToleranceLevel = 0.00001; % NLLSF parameter, tells change in parameter magnitude, if small then the result was stable
N_nllsf_iterations = 10; % number of iterations before we give up

% % % SWOT_at_S_P_G
BIN_EDGES = [(-dBIN/2):[dBIN]:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_SWOT_moor_12hr,Separation_SWOT_moor_12hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_SWOT_moor_12hr, m2_to_cm2*StructFunc_SWOT_moor_12hr, BIN_EDGES) - ...
         interval_stdofmean(Separation_SWOT_moor_12hr, m2_to_cm2*StructFunc_SWOT_moor_12hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['SWOT 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')
SF_avg = mean(SF_MAT_swot,2,'omitnan') - std(SF_MAT_swot,0,2,'omitnan')./sqrt(sum(isfinite(SF_MAT_swot(:,:)), 2));
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:dsearchn(DIST_VEC,40)), DIST_VEC(2:dsearchn(DIST_VEC,40)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,40))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:dsearchn(DIST_VEC,90)), DIST_VEC(2:dsearchn(DIST_VEC,90)),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['SWOT (all) to ' num2str(DIST_VEC(dsearchn(DIST_VEC,90))) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.1hr
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_1hr,Separation_S_P_600m_1hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_1hr, m2_to_cm2*StructFunc_S_P_600m_1hr, BIN_EDGES) - ...
         interval_stdofmean(Separation_S_P_600m_1hr, m2_to_cm2*StructFunc_S_P_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m/1hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SP.600m.24hr
BIN_EDGES = [(-dBIN/2):dBIN:1.1]*(0.92)*DD; % initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_600m_24hr,Separation_S_P_600m_24hr,BIN_EDGES); BIN_CENTR = BIN_CENTR(isfinite(BIN_CENTR));
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_600m_24hr, m2_to_cm2*StructFunc_S_P_600m_24hr, BIN_EDGES) - ...
         interval_stdofmean(Separation_S_P_600m_24hr, m2_to_cm2*StructFunc_S_P_600m_24hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(5:[end-1]),BIN_CENTR(5:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/M 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:5),BIN_CENTR(2:5),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/24hr/M to ' num2str(BIN_CENTR(5)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')


% % % SPG.600m.1hr
BIN_EDGES = [(-dBIN/2/2):[dBIN/2]:[14*dBIN/2/2]]; BIN_EDGES =  [BIN_EDGES, [BIN_EDGES(end)+dBIN]:[dBIN]:1.1]*(0.92)*DD;% initial bin edges
BIN_CENTR = interval_avg(Separation_S_P_G_600m_1hr,Separation_S_P_G_600m_1hr,BIN_EDGES);
BIN_EDGES = [[ BIN_CENTR(1) - [BIN_CENTR(2) - BIN_CENTR(1)]/2 ], ...
               [BIN_CENTR(2:end) + BIN_CENTR(1:[end-1])]/2, ...
               [BIN_CENTR(end) + [BIN_CENTR(end) - BIN_CENTR(end-1)]/2] ];
SF_avg = interval_avg(Separation_S_P_G_600m_1hr, m2_to_cm2*StructFunc_S_P_G_600m_1hr, BIN_EDGES) - ...
         interval_stdofmean(Separation_S_P_G_600m_1hr, m2_to_cm2*StructFunc_S_P_G_600m_1hr, BIN_EDGES);
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:[end-1]),BIN_CENTR(2:[end-1]),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
% [NLLSF_COEF,~,~,~] = ...
%             nonlinear_lsqf(SF_avg(8:[end-1]),BIN_CENTR(8:[end-1]),...
%             FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
% disp(['600m24hr/MG 40 to ' num2str(BIN_CENTR([end-1])) ' km: ' num2str(-NLLSF_COEF(2)-1)])
[NLLSF_COEF,~,~,~] = ...
            nonlinear_lsqf(SF_avg(2:8),BIN_CENTR(2:8),...
            FitBasisFunction,FitParameters0,FitBasisDerivatives,ToleranceLevel,N_nllsf_iterations,[]);
disp(['600m/1hr/MG to ' num2str(BIN_CENTR(8)) ' km: ' num2str(-NLLSF_COEF(2)-1)])
disp(' ')







%%

%% Auxiliary function

function Vq = interp1IA_function(X,V,Xq,dX)
    Vq = nan(size(Xq));
    for ii = 1:length(Xq)
        Vq(ii) = mean(V(X > [Xq(ii) - dX/2] & X <= [Xq(ii) + dX/2]),'omitnan');
    end
end

function V_avg = interval_avg(X,V,X_int)
    % X_int = edges of bins
    % X = location of data
    % V = data
    % V_avg = interval-averaged data
    V_avg = nan(size(X_int(2:end)));
    for ii = 1:[length(X_int) - 1]
        V_avg(ii) = mean(V(X > X_int(ii) & X < X_int(ii+1)),'omitnan');
    end
end

function V_stdofmean = interval_stdofmean(X,V,X_int)
    % X_int = edges of bins
    % X = location of data
    % V = data
    % V_stdofmean = std of mean = std/sqrt(N)
    V_stdofmean = nan(size(X_int(2:end)));
    for ii = 1:[length(X_int) - 1]
        V_stdofmean(ii) = std(V(X > X_int(ii) & X < X_int(ii+1)),'omitnan')/...
            sqrt(sum(isfinite(V(X > X_int(ii) & X < X_int(ii+1)))));
    end
end

function errorbar_stdofmean(bin_center, sep_vec, sf_vec, bin_edges, varargin)
    % Custom plotting function so that the plotting window doesn't get co
    % cluttered.
    if nargin == 4
        errorbar(bin_center, ...
            interval_avg(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            '.-', 'MarkerSize',25,'LineWidth',2)
    elseif nargin == 5
        errorbar(bin_center, ...
            interval_avg(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            '.-', 'MarkerSize',25,'LineWidth',2,'Color',varargin{1})
    elseif nargin == 6
        errorbar(bin_center, ...
            interval_avg(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            interval_stdofmean(sep_vec,sf_vec,bin_edges), ...
            varargin{2}, 'MarkerSize',25,'LineWidth',1,'Color',varargin{1})
    else
        error('4, 5, or 6 inputs only')
    end
end

function V_avg = interval_median(X,V,X_int)
    % X_int = edges of bins
    % X = location of data
    % V = data
    % V_avg = interval-averaged data
    V_avg = nan(size(X_int(2:end)));
    for ii = 1:[length(X_int) - 1]
        V_avg(ii) = median(V(X > X_int(ii) & X < X_int(ii+1)),'omitnan');
    end
end
