# cd /mnt/flow/swot/Jinbo_Analysis/Luke_Analysis/FullAnalysis/PROF
cd /mnt/flow/swot/Analysis_Luke/Moorings2/PROF/
# cd /home/kachelein/MATLAB/02.2024/Moorings2/PROF/

# 0th operation: combine the deparated P1 and P5 moorings, each of which have 2 profiler files
## Skip this for OSM and only use the longer second-half record, even though some of the cal/val period is missings
# Done, by running PROF_Combine_Disjoint_Data.m separately in MATLAB

# 0.5th operation: calculate total QC_FLAG, DEPTH, and PROF_NUM for P-moorings
nohup matlab -nodisplay -nosplash < P_mooring_preQC.m > P_preQC_outfile.txt &

# First run the L2 improvement in Python:
nohup bash L2_to_L2_JPLQC_post_launch_CTDPROF.sh & # shell script runs: python3 L2_to_L2_JPLQC_post_launch_CTDPROF.py

# Next calculate density using gsw.density.rho:
python3 gsw_density_from_moorings.py

# Calculate steric height using MATLAB:
nohup matlab -nodisplay -nosplash < StericHeight_CastAvg_AllMoorings_Anomaly.m > steric_height_outfile.txt &

# Calculate the correction to steric height due to the varying depth of the water column (at the top):
# TBD

# Calculate the effect of missing data at depth on steric height error:
#nohup matlab -nodisplay -nosplash <StericHeightAnomaly_GapError_Server.m  > steric_height_error_outfile_.txt &

date
date +"%FORMAT"
t_var=$(date)
t_var=`date`
echo "Generated by running </mnt/flow/swot/Analysis_Luke/Moorings2/Run_Full_Analysis_PROF.sh>.  Time last run: $t_var" > version_info.txt

echo "Done processing profilers"

echo "Now that profilers have been processed, be sure to run ./StericHeight_Gridded_PROF_and_FIXED.m and ./StericHeight_Pmoorings_Gridded_PROF.m after the fixed CTDs have all been processed as well." 
