## Copy over the newest VER002 files after verifying that the first argument names the newest files available:
#cp /mnt/flow/swot/calval/Data/insitu_mooring/mooring.ucsd.edu/swot2/swot2_s*/nc/*FIXED*END20230704_RT_VER002.nc /mnt/flow/swot/calval/Data/insitu_mooring/JPL_QC/FIXED_CTD/
#cd /mnt/flow/swot/calval/Data/insitu_mooring/JPL_QC/FIXED_CTD/
cd /mnt/flow/swot/Analysis_Luke/Moorings2/FIXED/
#mv SWOTPOSTLAUNCH_L2_MOORING-S4_CTD-FIXED_START20230227_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S4_CTD-FIXED_START20230227_END20230704_RT_VER002.nc 
#mv SWOTPOSTLAUNCH_L2_MOORING-S3_CTD-FIXED_START20230228_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S3_CTD-FIXED_START20230228_END20230704_RT_VER002.nc
#mv SWOTPOSTLAUNCH_L2_MOORING-S2_CTD-FIXED_START20230303_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S2_CTD-FIXED_START20230303_END20230704_RT_VER002.nc
#mv SWOTPOSTLAUNCH_L2_MOORING-S1_CTD-FIXED_START20230304_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S1_CTD-FIXED_START20230304_END20230704_RT_VER002.nc
#cd /mnt/flow/swot/Jinbo_Analysis/Luke_Analysis/FullAnalysis/FIXED
#
#cp /mnt/flow/swot/calval/Data/insitu_mooring_postcampaign/swot2_s*/nc/*FIXED*VER01.nc /mnt/flow/swot/Analysis_Luke/Moorings_Data/FIXED_CTD/
#cd /mnt/flow/swot/Analysis_Luke/Moorings_Data/FIXED_CTD/
#? mv SWOTPOSTLAUNCH_L2_MOORING-S4_CTD-FIXED_START20230227_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S4_CTD-FIXED_START20230227_END20230704_RT_VER002.nc
#? mv SWOTPOSTLAUNCH_L2_MOORING-S3_CTD-FIXED_START20230228_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S3_CTD-FIXED_START20230228_END20230704_RT_VER002.nc
#? mv SWOTPOSTLAUNCH_L2_MOORING-S2_CTD-FIXED_START20230303_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S2_CTD-FIXED_START20230303_END20230704_RT_VER002.nc
#? mv SWOTPOSTLAUNCH_L2_MOORING-S1_CTD-FIXED_START20230304_END20230704_RT_VER002.nc SWOTPOSTLAUNCH_L2_JPLQC_MOORING-S1_CTD-FIXED_START20230304_END20230704_RT_VER002.nc
#cd /mnt/flow/swot/Analysis_Luke/Moorings/FIXED

## Copy over FIXED data
cp /mnt/flow/swot/calval/Data/insitu_mooring_postcampaign/swot2_*/nc/*_L2_*FIXED* /mnt/flow/swot/Analysis_Luke/Moorings2/DATA/

## Move FIXED files to ../DATA/FIXED/
cp ../DATA/*FIXED*.nc ../DATA/FIXED/

## Calculate depth from pressure:
## python3 gsw_depth_from_deep_moorings_fixed.py
## This is now included in the SIO analysis

## Add in the QC variable so that the next step can save over it
nohup matlab -nodisplay -nosplash < create_QC_FLAG.m > create_QC_FLAG.txt &

## Additional quality control seems to be unnecessary for the fixed CTDs, but run QC check anyway:
python3 L2_to_L2_JPLQC_post_launch_CTDFIXED.py

## Remove stragglers without JPLQC mark (different from PROF where these are in a different directory; there is no good reason, I just never made the two processes congruent):
rm /mnt/flow/swot/Analysis_Luke/Moorings2/DATA/FIXED/*L2_MOORING*.nc

## Next, calculate density:
python3 gsw_density_from_moorings_fixed.py

#echo "MATLAB stage running now"
## Steric height calculation:
#nohup matlab -nodisplay -nosplash < StericHeight_from_FixedCTDs.m > steric_height_error_outfile_.txt &
nohup matlab -nodisplay -nosplash < StericHeight_from_FixedCTDs_including_gap.m > steric_height_withgap_error_outfile.txt &

# Calculate the correction to steric height due to the varying depth of the water column (at the bottom):
# TBD

date
date +"%FORMAT"
t_var=$(date)
t_var=`date`
# echo "Generated by running </mnt/flow/swot/Jinbo_Analysis/Luke_Analysis/FullAnalysis/Run_Full_Analysis_FIXED.sh>.  Time last run: $t_var" > version_info.txt
echo "Generated by running </mnt/flow/swot/Analysis_Luke/Moorings/Run_Full_Analysis_FIXED.sh>.  Time last run: $t_var" > version_info.txt

echo "Done processing fixed CTDs"

# echo "Now that fixed CTDs have been processed, be sure to run /FullAnalysis/StericHeight_Gridded_PROF_and_FIXED.m and /FullAnalysis/StericHeight_Pmoorings_Gridded_PROF.m after the profilers have all been processed as well."
echo "Now that fixed CTDs have been processed, be sure to run ./StericHeight_Gridded_PROF_and_FIXED.m and ./StericHeight_Pmoorings_Gridded_PROF.m after the profilers have all been processed as well."  
